apiVersion: v1
kind: Service
metadata:
  namespace: arct
  name: gatewayapi-service
spec:
  selector:
    app: gatewayapi-template
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
