apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arct
  name: jenkins-pvc
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
