apiVersion: v1
kind: Service
metadata:
  namespace: arct
  name: userapi-service
spec:
  selector:
    app: userapi-template
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
