apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fileservice
  template:
    metadata:
      labels:
        app: fileservice
    spec:
      containers:
      - name: fileservice
        image: fileservice:local
        ports:
        - containerPort: 80
 